# Generated by Django 4.0.4 on 2022-06-02 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['key', 'value'], name='ontology_ta_key_75e04e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('key', 'value'), name='ontology_tag_unique_kv'),
        ),
        migrations.AddField(
            model_name='entity',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ontology.tag'),
        ),
    ]
