# Generated by Django 4.0.5 on 2022-06-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='domain',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='ontology.domain'),
            preserve_default=False,
        ),
    ]
