# Generated by Django 4.0.3 on 2022-05-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_alter_entity_options_alter_dummy_entity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entitym2mtag',
            table='core_entity_tag',
        ),
    ]
