# Generated by Django 4.0.4 on 2022-05-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entitym2mtag_entity_alter_entitym2mtag_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummy',
            options={'verbose_name_plural': 'dummies'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.comment'),
        ),
    ]
